<!doctype html>

<html lang="pt">

	<head>
		<meta charset="utf-8">
		<title><?php echo APP_NAME; ?></title>
		<link rel="stylesheet" href="\libs\bootstrap-3.3.7-dist\css\bootstrap.css">
	</head>

<body>

	<header>
		

	</header>
	<main class="container">
	
		<button class="btn btn-primary" >Teste</button>
	</main>


	<footer>
		

	</footer>
	
	<script src="js/scripts.js"></script>

</body>

</html>
