    <footer>
    </footer>

    <script src="/libs/jquery/jquery-3.2.1.min.js" type="text/javascript"></script>
    <script src="/libs/bootstrap-3.3.7-dist/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/libs/jquery/jquery-3.2.1.min.js" type="text/javascript"></script>
    <script src="/libs/canvasjs-1.9.8/canvasjs.min.js" type="text/javascript"></script>
        
    <script src="/js/scripts.js" type="text/javascript"></script>
 
</body>

</html>
