<!doctype html>

<html lang="pt">

	<head>
		<meta charset="utf-8">
		<title><?php echo APP_NAME; ?></title>
		<link rel="stylesheet" href="\libs\bootstrap-3.3.7-dist\css\bootstrap.css">
	</head>

<body>

	<header>
		

<nav class="navbar navbar-default">
   <div class="container-fluid">
      <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar" />
            <span class="icon-bar" />
            <span class="icon-bar" />
         </button>
         <a class="navbar-brand" href="#"><?php echo APP_NAME; ?></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav">
            <li class="<?php if(@!$_GET['controller']) echo 'active' ?>">
               <a href="/">Inicio</a>
            </li>
            <li class="<?php if(@$_GET['controller'] == "users") echo 'active' ?>">
               <a href="?controller=users&action=index">Alunos</a>
            </li>
            <li>
               <a href="#">Professores</a>
            </li>
             <li>
               <a href="#">Notas</a>
            </li>
             <li>
               <a href="#">Frequencia</a>
            </li>
            
         </ul>
         
      </div>
      <!--/.nav-collapse -->
   </div>
   <!--/.container-fluid -->
</nav>

	</header>