<?php include MY_FOLDER . "/../app/View/Layouts/header.phtml"; ?>
 

<div class="container">     
    
    <?php if (@$_GET["ok"]): ?>
        <div class="alert alert-success">
            <?php echo $_GET["ok"] ?>
        </div>
    <?php endif; ?>
    <div>
        <a href="#" 
            data-toggle="modal" data-target="#myModal"
            class="btn btn-primary pull-right">
            <span class="glyphicon glyphicon-search"></span>
        </a>
        <a href="/?controller=users&action=add" class="btn btn-primary pull-right">
            <span class="glyphicon glyphicon-plus" ></span>
            Cadastrar novos
        </a>
    </div>
    
    <table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Cpf</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user):?> 
        <tr>
            <td><?php echo $user->id ?></td>
            <td><?php echo $user->name ?></td>
            <td><?php echo $user->cpf ?></td>
            <td><?php echo $user->email ?></td>
            <td>
                <a class="btn btn-warning"  
                   href="/?controller=users&action=edit&id=<?php echo $user->id ?>" >
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a class="btn btn-danger" 
                   onclick="return confirm ('Tem certeza?')" 
                   href="/?controller=users&action=delete&id=<?php echo $user->id ?>" >
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
    
    <div>
        Exibindo página x
        de um total de 
        <?php echo $pages ?>
        páginas
    </div>
    
    <div class="text-center" >
        <?php for($i = 1; $i <= $pages; $i++): ?>
        <ul class="pagination" >
            <li>
                <a href="/?controller=users&action=index&page=<?php echo $i ?>" >
                    <?php echo $i ?>
                </a>
            </li>
        </ul>
        <?php endfor; ?>
    </div>
   
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Pesquisar</h4>
      </div>
      <div class="modal-body">
        <form method="get" action="" >
            <div class="form-group">
                <div class="col-md-10">
                    <input id="txtQuery" 
                           name="q" 
                           type="text" placeholder="Pesquisar..." 
                           class="form-control">
                </div>
                <input name="controller" value="users" type="hidden" />
                <input name="action" value="query" type="hidden" />
                <div class="col-md-2">
                    <button id="singlebutton" name="singlebutton" class="btn btn-primary">
                        OK
                    </button>
                </div>
            </div>
        </form>           
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>
    
    

<?php include MY_FOLDER . "/../app/View/Layouts/footer.phtml"; ?>